FROM python:3.13-slim

RUN pip install --no-cache-dir poetry

WORKDIR /app

COPY pyproject.toml ./
RUN poetry install --no-root --no-interaction

COPY read_and_index.py ./
COPY indexer-*.toml ./
COPY data/ ./data/

ENTRYPOINT ["poetry", "run", "python", "read_and_index.py"]
CMD ["data/Database-Bataafse-Politieke-Tijdschriften-V3.xlsx"]
