[index]
full_text="yes"
name="tijdschriften-plaatsnaam"
record="yes"

[index.input]
format="json"

[index.id]
path="jmes:rowId"
type="keyword"

[index.facet.plaatsId]
path="jmes:Plaats_ID"
type="keyword"

[index.facet.plaatsnaam]
path="jmes:Name"
type="text"

[index.facet.land]
path="jmes:Land"
type="text"

[index.facet.coordinaten]
path="jmes:{ breedteGraad: Latitude, lengteGraad: Longitude }"
type="nested"
