[index]
full_text="yes"
name="tijdschriften-personen"
record="yes"

[index.input]
format="json"

[index.id]
path="jmes:rowId"
type="keyword"

[index.facet.persoonId]
path="jmes:ID_def"
type="keyword"

[index.facet.persoonsNaam]
path="jmes:Name"
type="text"

[index.facet.geboorteJaar]
path="jmes:geboortejaar"
type="text"

[index.facet.sterfJaar]
path="jmes:sterfjaar"
type="text"

[index.facet.bioPortaal]
path="jmes:Bioportaal"
type="text"

[index.facet.bioNummer]
path="jmes:Bionummer"
type="text"

[index.facet.politiekePositie]
path="jmes:\"Politieke positie\""
type="text"

[index.facet.eersteBeroep]
path="jmes:Beroep_1"
type="text"

[index.facet.eersteBeroepOpmerking]
path="jmes:Beroep_1_opmerking"
type="keyword"

[index.facet.tweedeBeroep]
path="jmes:Beroep_2"
type="text"

[index.facet.derdeBeroep]
path="jmes:Beroep_3"
type="text"
