[index]
full_text="yes"
record="yes"

[index.input]
format="json"

[index.id]
path="jmes:rowId"
type="keyword"

[index.facet.uitgeverId]
path="jmes:Uitgever_ID_nieuw"
type="text"

[index.facet.uitgever]
path="jmes:Uitgeverij"
type="keyword"

[index.facet.eersteGeneratieId]
path="jmes:Eerste_generatie.id"
type="keyword"

[index.facet.eersteGeneratieNaam]
path="jmes:Eerste_generatie.Name"
type="keyword"

[index.facet.tweedeGeneratieId]
path="jmes:Tweede_generatie.id"
type="keyword"

[index.facet.tweedeGeneratieNaam]
path="jmes:Tweede_generatie.Name"
type="keyword"

[index.facet.plaats1Id]
path="jmes:Plaats1.id"
type="keyword"

[index.facet.plaats1Naam]
path="jmes:Plaats1.name"

[index.facet.plaats2Id]
path="jmes:Plaats2.id"
type="text"

[index.facet.plaats2Naam]
path="jmes:Plaats2.name"
type="text"

[index.facet.plaats3Id]
path="jmes:Plaats3.id"
type="text"

[index.facet.plaats3Naam]
path="jmes:Plaats3.name"
type="text"

[index.facet.politiekSignatuur]
path="jmes:\"Politiek signatuur\""
type="text"

[index.facet.bestaan]
path="jmes:Bestaan"
type="text"
