[index]
full_text="yes"
record="yes"

[index.input]
format="json"

[index.id]
path="jmes:rowId"
type="keyword"

[index.facet.uitgeverId]
path="jmes:Uitgever_ID_nieuw"
type="text"

[index.facet.uitgever]
path="jmes:Uitgeverij"
type="keyword"

[index.facet.eersteGeneratieId]
path="jmes:Eerste_generatie.rowId"
type="keyword"

[index.facet.eersteGeneratieNaam]
path="jmes:Eerste_generatie.Naam"
type="keyword"

[index.facet.tweedeGeneratieId]
path="jmes:Tweede_generatie.rowId"
type="keyword"

[index.facet.tweedeGeneratieNaam]
path="jmes:Tweede_generatie.Naam"
type="keyword"

[index.facet.eerstePlaatsId]
path="jmes:Plaats1.rowId"
type="keyword"

[index.facet.eerstePlaatsNaam]
path="jmes:Plaats1.Name"

[index.facet.tweedePlaatsId]
path="jmes:Plaats2.rowId"
type="text"

[index.facet.tweedePlaatsNaam]
path="jmes:Plaats2.Name"
type="text"

[index.facet.derdePlaatsId]
path="jmes:Plaats3.rowId"
type="text"

[index.facet.derdePlaatsNaam]
path="jmes:Plaats3.Name"
type="text"

[index.facet.politiekSignatuur]
path="jmes:Politiek_signatuur"
type="text"

[index.facet.bestaan]
path="jmes:Bestaan"
type="text"
