[index]
full_text="yes"
record="yes"

[index.input]
format = "json"

[index.id]
path = "jmes:rowId"
type = "keyword"

[index.facet.tijdschriftId]
path = "jmes:Tijdschrift_ID_Nieuw"
type = "keyword"

[index.facet.uitgeverId]
path = "jmes:Uitgever.rowId"
type = "keyword"

[index.facet.uitgever]
path = "jmes:Uitgever.Uitgeverij"
type = "keyword"

[index.facet.drukker]
path = "jmes:Drukker.Uitgeverij"
type = "keyword"

[index.facet.plaatsId]
path = "jmes:Plaats1.rowId"
type = "keyword"

[index.facet.plaats]
path = "jmes:Plaats1.name"
type = "keyword"

[index.facet.titel]
path = "jmes:Titel1"
type = "keyword"

[index.facet.aanvullendeTitels]
path = """
jmes:[
    { titel: Titel2, vanaf: Titel2_vanaf },
    { titel: Titel3, vanaf: Titel3_vanaf },
    { titel: Titel4, vanaf: Titel4_vanaf },
    { titel: Titel5, vanaf: Titel5_vanaf },
    { titel: Titel6, vanaf: Titel6_vanaf },
    { titel: Titel7, vanaf: Titel7_vanaf }
]
"""
type = "nested"

[index.facet.vormTijdschrift]
path = "jmes:Vorm_Tijdschrift"
type = "keyword"

[index.facet.typeTijdschrift]
path = "jmes:Type_Tijdschrift"
type = "keyword"

[index.facet.politiekePositie]
path = "jmes:\"Politieke-Positie\""
type = "keyword"

[index.facet.eersteNummerJaar]
path = "jmes:Eerste_nr_JAAR"
type = "number"

[index.facet.laatsteNummerJaar]
path = "jmes:Laatste_nr_JAAR"
type = "text"

[index.facet.korteOmschrijvingInhoud]
path = "jmes:Korte_omschrijving_inhoud"
type = "text"

[index.facet.verantwoordingSelectie]
path = "jmes:Verantwoording_selectie"
type = "text"

[index.facet.toelichtingRedacteurAuteur]
path = "jmes:\"Toelichting_redacteur-auteur\""
type = "text"