[index]
full_text="yes"
name="tijdschriften-uitgever_drukker"
record="yes"

[index.input]
format="json"

[index.id]
path="jmes:rowId"
type="keyword"

[index.facet.uitgeverId]
path="jmes:Uitgever_ID_nieuw"
type="text"

[index.facet.uitgever]
path="jmes:Uitgeverij"
type="text"

[index.facet.eersteGeneratieId]
path="jmes:Eerste_generatie_ID"
type="keyword"

[index.facet.tweedeGeneratieId]
path="jmes:Tweede_generatie_ID"
type="keyword"

[index.facet.plaats1Id]
path="jmes:Plaats1_ID"
type="text"

[index.facet.plaats1Opmerking]
path="jmes:Plaats1_opmerking"
type="text"

[index.facet.plaats2Id]
path="jmes:Plaats2_ID"
type="text"

[index.facet.plaats3Id]
path="jmes:Plaats3_ID"
type="text"

[index.facet.politiekSignatuur]
path="jmes:\"Politiek signatuur\""
type="text"

[index.facet.bestaan]
path="jmes:Bestaan"
type="text"
