services:
  mongo:
    container_name: panoptes-mongo
    image: registry.diginfra.net/tsd/hi-bataafse-politieke-tijdschriften-mongo:latest
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' > /dev/null" ]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    networks:
      - pol-tijdschriften

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: panoptes-elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null" ]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - es-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2g
    restart: unless-stopped
    networks:
      - pol-tijdschriften

  panoptes:
    container_name: panoptes-api
    image: registry.diginfra.net/tsd/panoptes-backend:hi-bataafse-politieke-tijdschriften
    environment:
      - ES_SCHEME=http
      - ES_HOST=panoptes-elasticsearch
      - ES_PORT=9200
      - MONGO_CONNECTION=mongodb://panoptes-mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy
      elastic:
        condition: service_healthy
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.panoptes-api.entrypoints=http"
      - "traefik.http.routers.panoptes-api.rule=Host(`bataafse-politieke-tijdschriften.dev.diginfra.org`) && PathPrefix(`/api`)"
      - "traefik.http.services.panoptes-api.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - pol-tijdschriften
      - traefik-public

  panoptes-browser:
    container_name: panoptes-react
    image: registry.diginfra.net/tsd/hi-bataafse-politieke-tijdschriften-browser:latest
    environment:
      - VITE_PANOPTES_URL=https://bataafse-politieke-tijdschriften.dev.diginfra.org
      - VITE_PANOPTES_IS_EMBEDDED=false
      - VITE_PANOPTES_DATASET=politieke-tijdschriften
      - VITE_PANOPTES_SEARCH_PATH=/$$dataset/search
      - VITE_PANOPTES_DETAIL_PATH=/$$dataset/details/$$id
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.panoptes-react.entrypoints=http"
      - "traefik.http.routers.panoptes-react.rule=Host(`bataafse-politieke-tijdschriften.dev.diginfra.org`)"
      - "traefik.http.services.panoptes-react.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - pol-tijdschriften
      - traefik-public

  indexer:
    container_name: bpt-indexer
    image: registry.diginfra.net/tsd/hi-bataafse-politieke-tijdschriften-indexer:latest
    command: ["data/Database-Bataafse-Politieke-Tijdschriften-V3.xlsx", "ALL"]
    environment:
      - ES_HOST=panoptes-elasticsearch
      - ES_PORT=9200
    depends_on:
      elastic:
        condition: service_healthy
    restart: no
    networks:
      - pol-tijdschriften

volumes:
  es-data:
  mongo-data:

networks:
  pol-tijdschriften:
    internal: true
  traefik-public:
    external: true
