services:

  mongo:
    container_name: panoptes-mongo
    image: registry.diginfra.net/tsd/hi-bataafse-politieke-tijdschriften-mongo:latest
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' > /dev/null" ]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    expose:
      - "27017"
    networks:
      - traefik-public

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: panoptes-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - "9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null" ]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - traefik-public

  panoptes:
    container_name: panoptes-api
    image: registry.diginfra.net/tsd/panoptes-backend:hi-bataafse-politieke-tijdschriften
    environment:
      - ES_SCHEME=http
      - ES_HOST=panoptes-elasticsearch
      - ES_PORT=9201
      - MONGO_CONNECTION=mongodb://panoptes-mongo:27018/
    depends_on:
      mongo:
        condition: service_healthy
      elastic:
        condition: service_healthy
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - traefik-public

  panoptes-browser:
    container_name: panoptes-react
    image: registry.diginfra.net/tsd/hi-bataafse-politieke-tijdschriften-browser:latest
    environment:
      - VITE_PANOPTES_URL=http://panoptes-api:8001
      - VITE_PANOPTES_IS_EMBEDDED=false
      - VITE_PANOPTES_DATASET=politieke-tijdschriften
      - VITE_PANOPTES_SEARCH_PATH=/\$dataset/search
      - VITE_PANOPTES_DETAIL_PATH=/\$dataset/details/\$id
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hi-bataafse-politieke-tijdschriften.entrypoints=http"
      - "traefik.http.routers.hi-bataafse-politieke-tijdschriften.rule=Host(`bataafse-politieke-tijdschriften.dev.diginfra.org`)"
      - "traefik.http.services.hi-bataafse-politieke-tijdschriften.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - traefik-public

  indexer:
    container_name: bpt-indexer
    image: registry.diginfra.net/tsd/hi-bataafse-politieke-tijdschriften-indexer:latest
    command: ["data/Database-Bataafse-Politieke-Tijdschriften-V3.xlsx", "ALL"]
    environment:
      - ES_HOST=panoptes-elasticsearch
      - ES_PORT=9201
    depends_on:
      elastic:
        condition: service_healthy
    networks:
      - traefik-public
    #profiles:
    #  - indexer

volumes:
  es-data:
  mongo-data:

networks:
  traefik-public:
    external: true
